trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - deployment: JA
    environment: 'IaCDevEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            name: DetermineResult
            inputs:
              targetType: inline
              script: |
                write-host "This is job Foo."

                write-host "##vso[task.setvariable variable=doThing;isOutput=true]Yes" #The variable doThing is set to true

          - script: echo $(DetermineResult.doThing)
            name: echovar

- stage: B
  dependsOn: A
  variables:
      varFromStageA: $[ stageDependencies.A.outputs['JA.JA.DetermineResult.doThing'] ]
      varFromStageA2: $[ stageDependencies.A.JA.outputs['DetermineResult.doThing'] ]
      varFromStageA3: $[ dependencies.A.outputs['JA.JA.DetermineResult.doThing'] ]
      varFromStageA4: $[ dependencies.A.JA.outputs['DetermineResult.doThing'] ]
      varFromStageA5: $[ stageDependencies.A.JA.outputs['JA.DetermineResult.doThing'] ]
  jobs:
  - job : JB2
    steps:
      - task: PowerShell@2
        name: DetermineResult
        inputs:
          targetType: inline
          script: |
            write-host "This is job Foo."
            write-host $(varFromStageA)
            write-host $(varFromStageA2)
            write-host $(varFromStageA3)
            write-host $(varFromStageA4)
            write-host $(varFromStageA5)

  - deployment: JB
    environment: 'IaCDevEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: echo "Hello world stage B first job"
          - script: echo $(varFromStageA)
          - task: PowerShell@2
            name: DetermineResult
            inputs:
              targetType: inline
              script: |
                write-host "This is job Foo."
                write-host $(varFromStageA)
                write-host $(varFromStageA2)
                write-host $(varFromStageA3)
                write-host $(varFromStageA4)
                write-host $(varFromStageA5)

