parameters:
  - name: SubscriptionId
    type: string
  - name: Location
    type: string
  - name: AzureResourceManagerConnection
    type: string 
  - name: Environment
    type: string

steps:
- task: DownloadBuildArtifacts@0
  displayName: Download Build Artifacts
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy Main Template
  inputs:
    azureResourceManagerConnection: '${{ parameters.AzureResourceManagerConnection }}'
    deploymentScope: 'Subscription'
    subscriptionId: '${{ parameters.SubscriptionId }}'
    location: ${{ parameters.Location }}
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/drop/templates/mainDeployment.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/drop/templates/parameters.${{ parameters.Environment }}.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: mainDeployments_outputs


- task: PowerShell@2
  displayName: 'Set outputs'
  name: SetOutputs
  inputs:
    targetType: inline
    script: |
      Write-Host $env:MAINDEPLOYMENTS_OUTPUTS
      $armOutputObj = $env:MAINDEPLOYMENTS_OUTPUTS | convertfrom-json
      Write-Host $armOutputObj

      echo "##vso[task.setvariable variable=kubeletPrincipalId;isOutput=true]$armOutputObj.kubeletIdentityPrincipalId.value"