parameters:
  - name: service_connection
    type: string 
  - name: working_directory 
    type: string 
    default: 'terraform'
  - name: terraformStateKey
    type: string
    default: ''
  - name: storageAccount
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: resourceGroup
    type: string
  - name: containerName
    type: string
  - name: environment
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    dependsOn: ${{ parameters.dependsOn }}
    steps:
      - template: ../task/init.yml
        parameters:
          service_connection: ${{ parameters.service_connection }}
          resourceGroup: ${{ parameters.resourceGroup }}
          storageAccount: ${{ parameters.storageAccount }}
          containerName: ${{ parameters.containerName }}
          terraformStateKey: ${{ parameters.terraformStateKey }}
          working_directory: ${{ parameters.working_directory }}

      - template: ../task/plan.yml
        parameters:
          service_connection: ${{ parameters.service_connection }}
          working_directory: ${{ parameters.working_directory }}
          environment: ${{ parameters.environment }}

      - task: CopyFiles@2
        displayName: Copy plan file
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/${{ parameters.working_directory }}
          Contents: '*.plan'
          TargetFolder: $(Build.ArtifactStagingDirectory)
        condition: succeededOrFailed()

      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact
        inputs:
          artifactName: terraformPlan-${{ parameters.environment }}
          targetPath: $(Build.ArtifactStagingDirectory)