parameters:   
  - name: service_connection
    type: string
  - name: working_directory
    type: string
    default: "terraform"
  - name: storageAccount
    type: string
  - name: resourceGroup
    type: string
  - name: containerName
    type: string
    default: "terraform-state"
  - name: publicNetworkAction
    type: string
  - name: allowedSubnetIds
    type: object
    default:
  - name: dependsOn
    type: object
    default: []

jobs:
  - job: TerraformPrerequisites
    displayName: Prerequisites for Terraform in Azure
    dependsOn:  ${{ parameters.dependsOn }}

    steps:
      - task: AzureCLI@2
        displayName: Create prerequisites
        inputs:
          azureSubscription: ${{ parameters.service_connection }}
          scriptType: "pscore"
          powerShellErrorActionPreference: "stop"
          scriptLocation: "inlineScript"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
          inlineScript: |
            $allowedSubnetIdsJson = '${{ convertToJson(parameters.allowedSubnetIds) }}'

            $allowedSubnetIds = @()
            if ($allowedSubnetIdsJson.StartsWith("[")) { # only deserialize if json starts with [, when specifying no values, the json will be empty or contain "" resulting in errors when deserializing
              $allowedSubnetIds = $allowedSubnetIdsJson |ConvertFrom-Json
            }

            ${{ parameters.working_directory }}/pipelines/job/createPrerequisites.ps1 `
              -resourceGroupName "${{ parameters.resourceGroup }}" `
              -storageAccountName  "${{ parameters.storageAccount }}" `
              -containerName "${{ parameters.containerName }}" `
              -publicNetworkAction "${{ parameters.publicNetworkAction }}" `
              -allowedSubnetIds $allowedSubnetIds
