parameters:
  - name: service_connection
    type: string 

jobs:
  - job: SetTerraformEnvironmentVariables
    displayName: Set Terraform Environment variables

    steps:
    - task: AzureCLI@2
      name: ExportTerraformEnvironmentVariables
      displayName: Set Terraform Environment variables
      inputs:
        azureSubscription: ${{ parameters.service_connection }}
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        scriptType: bash
        inlineScript: |
          set -eu

          subscriptionId=$(az account show --query id -o tsv)
          
          export ARM_SUBSCRIPTION_ID=$subscriptionId
          export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)

          echo "##vso[task.setvariable variable=subscriptionId;isOutput=true;]$subscriptionId"