# specific path build
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-terraform

pool:
  vmImage: ubuntu-latest

variables:
  working_directory: ./azure-terraform
  project_name: terraformdemo

stages:
  - template: release-stage.yml
    parameters:
      project_name: ${{ variables.project_name }}
      environment: dev
      service_connection: 'Azure MVP Sponsorship'
      working_directory: $(working_directory)

  - template: release-stage.yml
    parameters:
      project_name: ${{ variables.project_name }}
      environment: prd
      service_connection: 'Azure MVP Sponsorship'
      working_directory: $(working_directory)